finish findById
GMSzebeni/diligent-cicd-practice pull request #2
Opened 2024-09-27 18:09 UTC by BlazsejKrisz

2024-09-28 08:21 UTC, GMSzebeni requested changes, later dismissed

2024-09-28 08:21 UTC, GMSzebeni commented on src/todo.js
> +  if (!todo) {
this should be moved to validation.js
(Also it is not working because you have not imported AppError)

2024-09-28 08:21 UTC, GMSzebeni commented on src/todo.js
> +  if (isNaN(id) || id === '') {
this should be moved to validation.js
there is no need for the second condition in this statement as if it has to be a number it cannot be a string, not even an empty one.
(Also it is not working because you have not imported AppError)

2024-09-28 08:21 UTC, GMSzebeni commented on src/todo.js
> +  const todoId = Number(id);
there is no need to assign if you previously checked if it is a number or not.

2024-09-28 08:21 UTC, GMSzebeni commented on src/todo.js
the task specifies that the new functionallity should be covered with tests - is there a specific reason you did not add the tests?

2024-09-28 14:06 UTC, kepelivi approved these changes
I think everything is ok, good job!

2024-09-29 18:27 UTC, GMSzebeni approved these changes

2024-09-29 18:27 UTC, GMSzebeni commented on src/app.js
> +        if (!todo) {
you may want to move this to the todo.js - not necessary

2024-09-29 18:27 UTC, GMSzebeni commented on src/app.js
> +        const todo = findById(todoStore, params[0]);
if you send the id (declaired in line 23) in instead of params[0] you don't need to reconvert it in todo.js.

2024-09-29 18:27 UTC, GMSzebeni commented on src/todo.js
> +  const numericId = Number(id)
no need to convert it to Number if you send the id in as Number already (see my comment in app.js)

2024-09-29 18:27 UTC, merged