complete todo
GMSzebeni/diligent-cicd-practice pull request #3
Opened 2024-09-28 09:58 UTC by kepelivi

Users are able to set a todo's 'done' status to completed. Functionality and validation are covered with tests.

2024-09-29 13:27 UTC, GMSzebeni requested changes

2024-09-29 13:27 UTC, GMSzebeni commented on src/validate.js
> +  if (typeof params !== 'string' && typeof params !== 'number') {
this checking is not necessary. i looked into this and command line arguments are always comming in as type strings. so there is also no need to validate boolean comming in in validate.spec.js.

2024-09-29 13:27 UTC, GMSzebeni commented on src/validate.js
if i am typing the command: node index.js complete 2 - it gets stuck on line 31 and I get the error: Id must be a numeric type. so the command does not work for me. it works if lines 31-33 are deleted.

2024-09-29 13:27 UTC, GMSzebeni commented on src/validate.spec.js
> +    const param2 = true;
not necessary to check - see my comment in validate.js

2024-09-30 13:14 UTC, GMSzebeni approved these changes

2024-09-30 14:23 UTC, BlazsejKrisz approved these changes
Seems good to me. Great job!

2024-09-30 14:23 UTC, merged